environment:
  matrix:
    - nodejs_version: "8"

init:
  - git config --global core.symlinks true

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - refreshenv
  - npm install

cache:
  - node_modules
  # - "%LOCALAPPDATA%\\Yarn"
  - '%APPDATA%\npm-cache' # npm cache

test_script:
  - pwd
  # debugging Appveyor build. More info:
  # https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - npm run test:prod
  - npm run build

# Don't actually build.
build: off

after_test:
  - npm run report-coverage
  - npm run semantic-release